CREATE TABLE `diary` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`content` LONGBLOB NULL,
	`date` VARCHAR(50) NULL DEFAULT NULL,
	`weather` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`mood` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`uname` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
CREATE TABLE `user` (
	`name` VARCHAR(50) NOT NULL,
	`pwd` VARCHAR(50) NULL DEFAULT NULL,
	`sex` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8_bin',
	`ans` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`tel` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`name`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
